#pragma once

#define FA_AD                                  0xf641
#define FA_ADDRESS_BOOK                        0xf2b9
#define FA_ADDRESS_CARD                        0xf2bb
#define FA_ADJUST                              0xf042
#define FA_AIR_FRESHENER                       0xf5d0
#define FA_ALIGN_CENTER                        0xf037
#define FA_ALIGN_JUSTIFY                       0xf039
#define FA_ALIGN_LEFT                          0xf036
#define FA_ALIGN_RIGHT                         0xf038
#define FA_ALLERGIES                           0xf461
#define FA_AMBULANCE                           0xf0f9
#define FA_AMERICAN_SIGN_LANGUAGE_INTERPRETING 0xf2a3
#define FA_ANCHOR                              0xf13d
#define FA_ANGLE_DOUBLE_DOWN                   0xf103
#define FA_ANGLE_DOUBLE_LEFT                   0xf100
#define FA_ANGLE_DOUBLE_RIGHT                  0xf101
#define FA_ANGLE_DOUBLE_UP                     0xf102
#define FA_ANGLE_DOWN                          0xf107
#define FA_ANGLE_LEFT                          0xf104
#define FA_ANGLE_RIGHT                         0xf105
#define FA_ANGLE_UP                            0xf106
#define FA_ANGRY                               0xf556
#define FA_ANKH                                0xf644
#define FA_APPLE_ALT                           0xf5d1
#define FA_ARCHIVE                             0xf187
#define FA_ARCHWAY                             0xf557
#define FA_ARROW_ALT_CIRCLE_DOWN               0xf358
#define FA_ARROW_ALT_CIRCLE_LEFT               0xf359
#define FA_ARROW_ALT_CIRCLE_RIGHT              0xf35a
#define FA_ARROW_ALT_CIRCLE_UP                 0xf35b
#define FA_ARROW_CIRCLE_DOWN                   0xf0ab
#define FA_ARROW_CIRCLE_LEFT                   0xf0a8
#define FA_ARROW_CIRCLE_RIGHT                  0xf0a9
#define FA_ARROW_CIRCLE_UP                     0xf0aa
#define FA_ARROW_DOWN                          0xf063
#define FA_ARROW_LEFT                          0xf060
#define FA_ARROW_RIGHT                         0xf061
#define FA_ARROW_UP                            0xf062
#define FA_ARROWS_ALT                          0xf0b2
#define FA_ARROWS_ALT_H                        0xf337
#define FA_ARROWS_ALT_V                        0xf338
#define FA_ASSISTIVE_LISTENING_SYSTEMS         0xf2a2
#define FA_ASTERISK                            0xf069
#define FA_AT                                  0xf1fa
#define FA_ATLAS                               0xf558
#define FA_ATOM                                0xf5d2
#define FA_AUDIO_DESCRIPTION                   0xf29e
#define FA_AWARD                               0xf559
#define FA_BABY                                0xf77c
#define FA_BABY_CARRIAGE                       0xf77d
#define FA_BACKSPACE                           0xf55a
#define FA_BACKWARD                            0xf04a
#define FA_BACON                               0xf7e5
#define FA_BALANCE_SCALE                       0xf24e
#define FA_BALANCE_SCALE_LEFT                  0xf515
#define FA_BALANCE_SCALE_RIGHT                 0xf516
#define FA_BAN                                 0xf05e
#define FA_BAND_AID                            0xf462
#define FA_BARCODE                             0xf02a
#define FA_BARS                                0xf0c9
#define FA_BASEBALL_BALL                       0xf433
#define FA_BASKETBALL_BALL                     0xf434
#define FA_BATH                                0xf2cd
#define FA_BATTERY_EMPTY                       0xf244
#define FA_BATTERY_FULL                        0xf240
#define FA_BATTERY_HALF                        0xf242
#define FA_BATTERY_QUARTER                     0xf243
#define FA_BATTERY_THREE_QUARTERS              0xf241
#define FA_BED                                 0xf236
#define FA_BEER                                0xf0fc
#define FA_BELL                                0xf0f3
#define FA_BELL_SLASH                          0xf1f6
#define FA_BEZIER_CURVE                        0xf55b
#define FA_BIBLE                               0xf647
#define FA_BICYCLE                             0xf206
#define FA_BIKING                              0xf84a
#define FA_BINOCULARS                          0xf1e5
#define FA_BIOHAZARD                           0xf780
#define FA_BIRTHDAY_CAKE                       0xf1fd
#define FA_BLENDER                             0xf517
#define FA_BLENDER_PHONE                       0xf6b6
#define FA_BLIND                               0xf29d
#define FA_BLOG                                0xf781
#define FA_BOLD                                0xf032
#define FA_BOLT                                0xf0e7
#define FA_BOMB                                0xf1e2
#define FA_BONE                                0xf5d7
#define FA_BONG                                0xf55c
#define FA_BOOK                                0xf02d
#define FA_BOOK_DEAD                           0xf6b7
#define FA_BOOK_MEDICAL                        0xf7e6
#define FA_BOOK_OPEN                           0xf518
#define FA_BOOK_READER                         0xf5da
#define FA_BOOKMARK                            0xf02e
#define FA_BORDER_ALL                          0xf84c
#define FA_BORDER_NONE                         0xf850
#define FA_BORDER_STYLE                        0xf853
#define FA_BOWLING_BALL                        0xf436
#define FA_BOX                                 0xf466
#define FA_BOX_OPEN                            0xf49e
#define FA_BOXES                               0xf468
#define FA_BRAILLE                             0xf2a1
#define FA_BRAIN                               0xf5dc
#define FA_BREAD_SLICE                         0xf7ec
#define FA_BRIEFCASE                           0xf0b1
#define FA_BRIEFCASE_MEDICAL                   0xf469
#define FA_BROADCAST_TOWER                     0xf519
#define FA_BROOM                               0xf51a
#define FA_BRUSH                               0xf55d
#define FA_BUG                                 0xf188
#define FA_BUILDING                            0xf1ad
#define FA_BULLHORN                            0xf0a1
#define FA_BULLSEYE                            0xf140
#define FA_BURN                                0xf46a
#define FA_BUS                                 0xf207
#define FA_BUS_ALT                             0xf55e
#define FA_BUSINESS_TIME                       0xf64a
#define FA_CALCULATOR                          0xf1ec
#define FA_CALENDAR                            0xf133
#define FA_CALENDAR_ALT                        0xf073
#define FA_CALENDAR_CHECK                      0xf274
#define FA_CALENDAR_DAY                        0xf783
#define FA_CALENDAR_MINUS                      0xf272
#define FA_CALENDAR_PLUS                       0xf271
#define FA_CALENDAR_TIMES                      0xf273
#define FA_CALENDAR_WEEK                       0xf784
#define FA_CAMERA                              0xf030
#define FA_CAMERA_RETRO                        0xf083
#define FA_CAMPGROUND                          0xf6bb
#define FA_CANDY_CANE                          0xf786
#define FA_CANNABIS                            0xf55f
#define FA_CAPSULES                            0xf46b
#define FA_CAR                                 0xf1b9
#define FA_CAR_ALT                             0xf5de
#define FA_CAR_BATTERY                         0xf5df
#define FA_CAR_CRASH                           0xf5e1
#define FA_CAR_SIDE                            0xf5e4
#define FA_CARET_DOWN                          0xf0d7
#define FA_CARET_LEFT                          0xf0d9
#define FA_CARET_RIGHT                         0xf0da
#define FA_CARET_SQUARE_DOWN                   0xf150
#define FA_CARET_SQUARE_LEFT                   0xf191
#define FA_CARET_SQUARE_RIGHT                  0xf152
#define FA_CARET_SQUARE_UP                     0xf151
#define FA_CARET_UP                            0xf0d8
#define FA_CARROT                              0xf787
#define FA_CART_ARROW_DOWN                     0xf218
#define FA_CART_PLUS                           0xf217
#define FA_CASH_REGISTER                       0xf788
#define FA_CAT                                 0xf6be
#define FA_CERTIFICATE                         0xf0a3
#define FA_CHAIR                               0xf6c0
#define FA_CHALKBOARD                          0xf51b
#define FA_CHALKBOARD_TEACHER                  0xf51c
#define FA_CHARGING_STATION                    0xf5e7
#define FA_CHART_AREA                          0xf1fe
#define FA_CHART_BAR                           0xf080
#define FA_CHART_LINE                          0xf201
#define FA_CHART_PIE                           0xf200
#define FA_CHECK                               0xf00c
#define FA_CHECK_CIRCLE                        0xf058
#define FA_CHECK_DOUBLE                        0xf560
#define FA_CHECK_SQUARE                        0xf14a
#define FA_CHEESE                              0xf7ef
#define FA_CHESS                               0xf439
#define FA_CHESS_BISHOP                        0xf43a
#define FA_CHESS_BOARD                         0xf43c
#define FA_CHESS_KING                          0xf43f
#define FA_CHESS_KNIGHT                        0xf441
#define FA_CHESS_PAWN                          0xf443
#define FA_CHESS_QUEEN                         0xf445
#define FA_CHESS_ROOK                          0xf447
#define FA_CHEVRON_CIRCLE_DOWN                 0xf13a
#define FA_CHEVRON_CIRCLE_LEFT                 0xf137
#define FA_CHEVRON_CIRCLE_RIGHT                0xf138
#define FA_CHEVRON_CIRCLE_UP                   0xf139
#define FA_CHEVRON_DOWN                        0xf078
#define FA_CHEVRON_LEFT                        0xf053
#define FA_CHEVRON_RIGHT                       0xf054
#define FA_CHEVRON_UP                          0xf077
#define FA_CHILD                               0xf1ae
#define FA_CHURCH                              0xf51d
#define FA_CIRCLE                              0xf111
#define FA_CIRCLE_NOTCH                        0xf1ce
#define FA_CITY                                0xf64f
#define FA_CLINIC_MEDICAL                      0xf7f2
#define FA_CLIPBOARD                           0xf328
#define FA_CLIPBOARD_CHECK                     0xf46c
#define FA_CLIPBOARD_LIST                      0xf46d
#define FA_CLOCK                               0xf017
#define FA_CLONE                               0xf24d
#define FA_CLOSED_CAPTIONING                   0xf20a
#define FA_CLOUD                               0xf0c2
#define FA_CLOUD_DOWNLOAD_ALT                  0xf381
#define FA_CLOUD_MEATBALL                      0xf73b
#define FA_CLOUD_MOON                          0xf6c3
#define FA_CLOUD_MOON_RAIN                     0xf73c
#define FA_CLOUD_RAIN                          0xf73d
#define FA_CLOUD_SHOWERS_HEAVY                 0xf740
#define FA_CLOUD_SUN                           0xf6c4
#define FA_CLOUD_SUN_RAIN                      0xf743
#define FA_CLOUD_UPLOAD_ALT                    0xf382
#define FA_COCKTAIL                            0xf561
#define FA_CODE                                0xf121
#define FA_CODE_BRANCH                         0xf126
#define FA_COFFEE                              0xf0f4
#define FA_COG                                 0xf013
#define FA_COGS                                0xf085
#define FA_COINS                               0xf51e
#define FA_COLUMNS                             0xf0db
#define FA_COMMENT                             0xf075
#define FA_COMMENT_ALT                         0xf27a
#define FA_COMMENT_DOLLAR                      0xf651
#define FA_COMMENT_DOTS                        0xf4ad
#define FA_COMMENT_MEDICAL                     0xf7f5
#define FA_COMMENT_SLASH                       0xf4b3
#define FA_COMMENTS                            0xf086
#define FA_COMMENTS_DOLLAR                     0xf653
#define FA_COMPACT_DISC                        0xf51f
#define FA_COMPASS                             0xf14e
#define FA_COMPRESS                            0xf066
#define FA_COMPRESS_ARROWS_ALT                 0xf78c
#define FA_CONCIERGE_BELL                      0xf562
#define FA_COOKIE                              0xf563
#define FA_COOKIE_BITE                         0xf564
#define FA_COPY                                0xf0c5
#define FA_COPYRIGHT                           0xf1f9
#define FA_COUCH                               0xf4b8
#define FA_CREDIT_CARD                         0xf09d
#define FA_CROP                                0xf125
#define FA_CROP_ALT                            0xf565
#define FA_CROSS                               0xf654
#define FA_CROSSHAIRS                          0xf05b
#define FA_CROW                                0xf520
#define FA_CROWN                               0xf521
#define FA_CRUTCH                              0xf7f7
#define FA_CUBE                                0xf1b2
#define FA_CUBES                               0xf1b3
#define FA_CUT                                 0xf0c4
#define FA_DATABASE                            0xf1c0
#define FA_DEAF                                0xf2a4
#define FA_DEMOCRAT                            0xf747
#define FA_DESKTOP                             0xf108
#define FA_DHARMACHAKRA                        0xf655
#define FA_DIAGNOSES                           0xf470
#define FA_DICE                                0xf522
#define FA_DICE_D20                            0xf6cf
#define FA_DICE_D6                             0xf6d1
#define FA_DICE_FIVE                           0xf523
#define FA_DICE_FOUR                           0xf524
#define FA_DICE_ONE                            0xf525
#define FA_DICE_SIX                            0xf526
#define FA_DICE_THREE                          0xf527
#define FA_DICE_TWO                            0xf528
#define FA_DIGITAL_TACHOGRAPH                  0xf566
#define FA_DIRECTIONS                          0xf5eb
#define FA_DIVIDE                              0xf529
#define FA_DIZZY                               0xf567
#define FA_DNA                                 0xf471
#define FA_DOG                                 0xf6d3
#define FA_DOLLAR_SIGN                         0xf155
#define FA_DOLLY                               0xf472
#define FA_DOLLY_FLATBED                       0xf474
#define FA_DONATE                              0xf4b9
#define FA_DOOR_CLOSED                         0xf52a
#define FA_DOOR_OPEN                           0xf52b
#define FA_DOT_CIRCLE                          0xf192
#define FA_DOVE                                0xf4ba
#define FA_DOWNLOAD                            0xf019
#define FA_DRAFTING_COMPASS                    0xf568
#define FA_DRAGON                              0xf6d5
#define FA_DRAW_POLYGON                        0xf5ee
#define FA_DRUM                                0xf569
#define FA_DRUM_STEELPAN                       0xf56a
#define FA_DRUMSTICK_BITE                      0xf6d7
#define FA_DUMBBELL                            0xf44b
#define FA_DUMPSTER                            0xf793
#define FA_DUMPSTER_FIRE                       0xf794
#define FA_DUNGEON                             0xf6d9
#define FA_EDIT                                0xf044
#define FA_EGG                                 0xf7fb
#define FA_EJECT                               0xf052
#define FA_ELLIPSIS_H                          0xf141
#define FA_ELLIPSIS_V                          0xf142
#define FA_ENVELOPE                            0xf0e0
#define FA_ENVELOPE_OPEN                       0xf2b6
#define FA_ENVELOPE_OPEN_TEXT                  0xf658
#define FA_ENVELOPE_SQUARE                     0xf199
#define FA_EQUALS                              0xf52c
#define FA_ERASER                              0xf12d
#define FA_ETHERNET                            0xf796
#define FA_EURO_SIGN                           0xf153
#define FA_EXCHANGE_ALT                        0xf362
#define FA_EXCLAMATION                         0xf12a
#define FA_EXCLAMATION_CIRCLE                  0xf06a
#define FA_EXCLAMATION_TRIANGLE                0xf071
#define FA_EXPAND                              0xf065
#define FA_EXPAND_ARROWS_ALT                   0xf31e
#define FA_EXTERNAL_LINK_ALT                   0xf35d
#define FA_EXTERNAL_LINK_SQUARE_ALT            0xf360
#define FA_EYE                                 0xf06e
#define FA_EYE_DROPPER                         0xf1fb
#define FA_EYE_SLASH                           0xf070
#define FA_FAN                                 0xf863
#define FA_FAST_BACKWARD                       0xf049
#define FA_FAST_FORWARD                        0xf050
#define FA_FAX                                 0xf1ac
#define FA_FEATHER                             0xf52d
#define FA_FEATHER_ALT                         0xf56b
#define FA_FEMALE                              0xf182
#define FA_FIGHTER_JET                         0xf0fb
#define FA_FILE                                0xf15b
#define FA_FILE_ALT                            0xf15c
#define FA_FILE_ARCHIVE                        0xf1c6
#define FA_FILE_AUDIO                          0xf1c7
#define FA_FILE_CODE                           0xf1c9
#define FA_FILE_CONTRACT                       0xf56c
#define FA_FILE_CSV                            0xf6dd
#define FA_FILE_DOWNLOAD                       0xf56d
#define FA_FILE_EXCEL                          0xf1c3
#define FA_FILE_EXPORT                         0xf56e
#define FA_FILE_IMAGE                          0xf1c5
#define FA_FILE_IMPORT                         0xf56f
#define FA_FILE_INVOICE                        0xf570
#define FA_FILE_INVOICE_DOLLAR                 0xf571
#define FA_FILE_MEDICAL                        0xf477
#define FA_FILE_MEDICAL_ALT                    0xf478
#define FA_FILE_PDF                            0xf1c1
#define FA_FILE_POWERPOINT                     0xf1c4
#define FA_FILE_PRESCRIPTION                   0xf572
#define FA_FILE_SIGNATURE                      0xf573
#define FA_FILE_UPLOAD                         0xf574
#define FA_FILE_VIDEO                          0xf1c8
#define FA_FILE_WORD                           0xf1c2
#define FA_FILL                                0xf575
#define FA_FILL_DRIP                           0xf576
#define FA_FILM                                0xf008
#define FA_FILTER                              0xf0b0
#define FA_FINGERPRINT                         0xf577
#define FA_FIRE                                0xf06d
#define FA_FIRE_ALT                            0xf7e4
#define FA_FIRE_EXTINGUISHER                   0xf134
#define FA_FIRST_AID                           0xf479
#define FA_FISH                                0xf578
#define FA_FIST_RAISED                         0xf6de
#define FA_FLAG                                0xf024
#define FA_FLAG_CHECKERED                      0xf11e
#define FA_FLAG_USA                            0xf74d
#define FA_FLASK                               0xf0c3
#define FA_FLUSHED                             0xf579
#define FA_FOLDER                              0xf07b
#define FA_FOLDER_MINUS                        0xf65d
#define FA_FOLDER_OPEN                         0xf07c
#define FA_FOLDER_PLUS                         0xf65e
#define FA_FONT                                0xf031
#define FA_FONT_AWESOME_LOGO_FULL              0xf4e6
#define FA_FOOTBALL_BALL                       0xf44e
#define FA_FORWARD                             0xf04e
#define FA_FROG                                0xf52e
#define FA_FROWN                               0xf119
#define FA_FROWN_OPEN                          0xf57a
#define FA_FUNNEL_DOLLAR                       0xf662
#define FA_FUTBOL                              0xf1e3
#define FA_GAMEPAD                             0xf11b
#define FA_GAS_PUMP                            0xf52f
#define FA_GAVEL                               0xf0e3
#define FA_GEM                                 0xf3a5
#define FA_GENDERLESS                          0xf22d
#define FA_GHOST                               0xf6e2
#define FA_GIFT                                0xf06b
#define FA_GIFTS                               0xf79c
#define FA_GLASS_CHEERS                        0xf79f
#define FA_GLASS_MARTINI                       0xf000
#define FA_GLASS_MARTINI_ALT                   0xf57b
#define FA_GLASS_WHISKEY                       0xf7a0
#define FA_GLASSES                             0xf530
#define FA_GLOBE                               0xf0ac
#define FA_GLOBE_AFRICA                        0xf57c
#define FA_GLOBE_AMERICAS                      0xf57d
#define FA_GLOBE_ASIA                          0xf57e
#define FA_GLOBE_EUROPE                        0xf7a2
#define FA_GOLF_BALL                           0xf450
#define FA_GOPURAM                             0xf664
#define FA_GRADUATION_CAP                      0xf19d
#define FA_GREATER_THAN                        0xf531
#define FA_GREATER_THAN_EQUAL                  0xf532
#define FA_GRIMACE                             0xf57f
#define FA_GRIN                                0xf580
#define FA_GRIN_ALT                            0xf581
#define FA_GRIN_BEAM                           0xf582
#define FA_GRIN_BEAM_SWEAT                     0xf583
#define FA_GRIN_HEARTS                         0xf584
#define FA_GRIN_SQUINT                         0xf585
#define FA_GRIN_SQUINT_TEARS                   0xf586
#define FA_GRIN_STARS                          0xf587
#define FA_GRIN_TEARS                          0xf588
#define FA_GRIN_TONGUE                         0xf589
#define FA_GRIN_TONGUE_SQUINT                  0xf58a
#define FA_GRIN_TONGUE_WINK                    0xf58b
#define FA_GRIN_WINK                           0xf58c
#define FA_GRIP_HORIZONTAL                     0xf58d
#define FA_GRIP_LINES                          0xf7a4
#define FA_GRIP_LINES_VERTICAL                 0xf7a5
#define FA_GRIP_VERTICAL                       0xf58e
#define FA_GUITAR                              0xf7a6
#define FA_H_SQUARE                            0xf0fd
#define FA_HAMBURGER                           0xf805
#define FA_HAMMER                              0xf6e3
#define FA_HAMSA                               0xf665
#define FA_HAND_HOLDING                        0xf4bd
#define FA_HAND_HOLDING_HEART                  0xf4be
#define FA_HAND_HOLDING_USD                    0xf4c0
#define FA_HAND_LIZARD                         0xf258
#define FA_HAND_MIDDLE_FINGER                  0xf806
#define FA_HAND_PAPER                          0xf256
#define FA_HAND_PEACE                          0xf25b
#define FA_HAND_POINT_DOWN                     0xf0a7
#define FA_HAND_POINT_LEFT                     0xf0a5
#define FA_HAND_POINT_RIGHT                    0xf0a4
#define FA_HAND_POINT_UP                       0xf0a6
#define FA_HAND_POINTER                        0xf25a
#define FA_HAND_ROCK                           0xf255
#define FA_HAND_SCISSORS                       0xf257
#define FA_HAND_SPOCK                          0xf259
#define FA_HANDS                               0xf4c2
#define FA_HANDS_HELPING                       0xf4c4
#define FA_HANDSHAKE                           0xf2b5
#define FA_HANUKIAH                            0xf6e6
#define FA_HARD_HAT                            0xf807
#define FA_HASHTAG                             0xf292
#define FA_HAT_WIZARD                          0xf6e8
#define FA_HAYKAL                              0xf666
#define FA_HDD                                 0xf0a0
#define FA_HEADING                             0xf1dc
#define FA_HEADPHONES                          0xf025
#define FA_HEADPHONES_ALT                      0xf58f
#define FA_HEADSET                             0xf590
#define FA_HEART                               0xf004
#define FA_HEART_BROKEN                        0xf7a9
#define FA_HEARTBEAT                           0xf21e
#define FA_HELICOPTER                          0xf533
#define FA_HIGHLIGHTER                         0xf591
#define FA_HIKING                              0xf6ec
#define FA_HIPPO                               0xf6ed
#define FA_HISTORY                             0xf1da
#define FA_HOCKEY_PUCK                         0xf453
#define FA_HOLLY_BERRY                         0xf7aa
#define FA_HOME                                0xf015
#define FA_HORSE                               0xf6f0
#define FA_HORSE_HEAD                          0xf7ab
#define FA_HOSPITAL                            0xf0f8
#define FA_HOSPITAL_ALT                        0xf47d
#define FA_HOSPITAL_SYMBOL                     0xf47e
#define FA_HOT_TUB                             0xf593
#define FA_HOTDOG                              0xf80f
#define FA_HOTEL                               0xf594
#define FA_HOURGLASS                           0xf254
#define FA_HOURGLASS_END                       0xf253
#define FA_HOURGLASS_HALF                      0xf252
#define FA_HOURGLASS_START                     0xf251
#define FA_HOUSE_DAMAGE                        0xf6f1
#define FA_HRYVNIA                             0xf6f2
#define FA_I_CURSOR                            0xf246
#define FA_ICE_CREAM                           0xf810
#define FA_ICICLES                             0xf7ad
#define FA_ICONS                               0xf86d
#define FA_ID_BADGE                            0xf2c1
#define FA_ID_CARD                             0xf2c2
#define FA_ID_CARD_ALT                         0xf47f
#define FA_IGLOO                               0xf7ae
#define FA_IMAGE                               0xf03e
#define FA_IMAGES                              0xf302
#define FA_INBOX                               0xf01c
#define FA_INDENT                              0xf03c
#define FA_INDUSTRY                            0xf275
#define FA_INFINITY                            0xf534
#define FA_INFO                                0xf129
#define FA_INFO_CIRCLE                         0xf05a
#define FA_ITALIC                              0xf033
#define FA_JEDI                                0xf669
#define FA_JOINT                               0xf595
#define FA_JOURNAL_WHILLS                      0xf66a
#define FA_KAABA                               0xf66b
#define FA_KEY                                 0xf084
#define FA_KEYBOARD                            0xf11c
#define FA_KHANDA                              0xf66d
#define FA_KISS                                0xf596
#define FA_KISS_BEAM                           0xf597
#define FA_KISS_WINK_HEART                     0xf598
#define FA_KIWI_BIRD                           0xf535
#define FA_LANDMARK                            0xf66f
#define FA_LANGUAGE                            0xf1ab
#define FA_LAPTOP                              0xf109
#define FA_LAPTOP_CODE                         0xf5fc
#define FA_LAPTOP_MEDICAL                      0xf812
#define FA_LAUGH                               0xf599
#define FA_LAUGH_BEAM                          0xf59a
#define FA_LAUGH_SQUINT                        0xf59b
#define FA_LAUGH_WINK                          0xf59c
#define FA_LAYER_GROUP                         0xf5fd
#define FA_LEAF                                0xf06c
#define FA_LEMON                               0xf094
#define FA_LESS_THAN                           0xf536
#define FA_LESS_THAN_EQUAL                     0xf537
#define FA_LEVEL_DOWN_ALT                      0xf3be
#define FA_LEVEL_UP_ALT                        0xf3bf
#define FA_LIFE_RING                           0xf1cd
#define FA_LIGHTBULB                           0xf0eb
#define FA_LINK                                0xf0c1
#define FA_LIRA_SIGN                           0xf195
#define FA_LIST                                0xf03a
#define FA_LIST_ALT                            0xf022
#define FA_LIST_OL                             0xf0cb
#define FA_LIST_UL                             0xf0ca
#define FA_LOCATION_ARROW                      0xf124
#define FA_LOCK                                0xf023
#define FA_LOCK_OPEN                           0xf3c1
#define FA_LONG_ARROW_ALT_DOWN                 0xf309
#define FA_LONG_ARROW_ALT_LEFT                 0xf30a
#define FA_LONG_ARROW_ALT_RIGHT                0xf30b
#define FA_LONG_ARROW_ALT_UP                   0xf30c
#define FA_LOW_VISION                          0xf2a8
#define FA_LUGGAGE_CART                        0xf59d
#define FA_MAGIC                               0xf0d0
#define FA_MAGNET                              0xf076
#define FA_MAIL_BULK                           0xf674
#define FA_MALE                                0xf183
#define FA_MAP                                 0xf279
#define FA_MAP_MARKED                          0xf59f
#define FA_MAP_MARKED_ALT                      0xf5a0
#define FA_MAP_MARKER                          0xf041
#define FA_MAP_MARKER_ALT                      0xf3c5
#define FA_MAP_PIN                             0xf276
#define FA_MAP_SIGNS                           0xf277
#define FA_MARKER                              0xf5a1
#define FA_MARS                                0xf222
#define FA_MARS_DOUBLE                         0xf227
#define FA_MARS_STROKE                         0xf229
#define FA_MARS_STROKE_H                       0xf22b
#define FA_MARS_STROKE_V                       0xf22a
#define FA_MASK                                0xf6fa
#define FA_MEDAL                               0xf5a2
#define FA_MEDKIT                              0xf0fa
#define FA_MEH                                 0xf11a
#define FA_MEH_BLANK                           0xf5a4
#define FA_MEH_ROLLING_EYES                    0xf5a5
#define FA_MEMORY                              0xf538
#define FA_MENORAH                             0xf676
#define FA_MERCURY                             0xf223
#define FA_METEOR                              0xf753
#define FA_MICROCHIP                           0xf2db
#define FA_MICROPHONE                          0xf130
#define FA_MICROPHONE_ALT                      0xf3c9
#define FA_MICROPHONE_ALT_SLASH                0xf539
#define FA_MICROPHONE_SLASH                    0xf131
#define FA_MICROSCOPE                          0xf610
#define FA_MINUS                               0xf068
#define FA_MINUS_CIRCLE                        0xf056
#define FA_MINUS_SQUARE                        0xf146
#define FA_MITTEN                              0xf7b5
#define FA_MOBILE                              0xf10b
#define FA_MOBILE_ALT                          0xf3cd
#define FA_MONEY_BILL                          0xf0d6
#define FA_MONEY_BILL_ALT                      0xf3d1
#define FA_MONEY_BILL_WAVE                     0xf53a
#define FA_MONEY_BILL_WAVE_ALT                 0xf53b
#define FA_MONEY_CHECK                         0xf53c
#define FA_MONEY_CHECK_ALT                     0xf53d
#define FA_MONUMENT                            0xf5a6
#define FA_MOON                                0xf186
#define FA_MORTAR_PESTLE                       0xf5a7
#define FA_MOSQUE                              0xf678
#define FA_MOTORCYCLE                          0xf21c
#define FA_MOUNTAIN                            0xf6fc
#define FA_MOUSE_POINTER                       0xf245
#define FA_MUG_HOT                             0xf7b6
#define FA_MUSIC                               0xf001
#define FA_NETWORK_WIRED                       0xf6ff
#define FA_NEUTER                              0xf22c
#define FA_NEWSPAPER                           0xf1ea
#define FA_NOT_EQUAL                           0xf53e
#define FA_NOTES_MEDICAL                       0xf481
#define FA_OBJECT_GROUP                        0xf247
#define FA_OBJECT_UNGROUP                      0xf248
#define FA_OIL_CAN                             0xf613
#define FA_OM                                  0xf679
#define FA_OTTER                               0xf700
#define FA_OUTDENT                             0xf03b
#define FA_PAGER                               0xf815
#define FA_PAINT_BRUSH                         0xf1fc
#define FA_PAINT_ROLLER                        0xf5aa
#define FA_PALETTE                             0xf53f
#define FA_PALLET                              0xf482
#define FA_PAPER_PLANE                         0xf1d8
#define FA_PAPERCLIP                           0xf0c6
#define FA_PARACHUTE_BOX                       0xf4cd
#define FA_PARAGRAPH                           0xf1dd
#define FA_PARKING                             0xf540
#define FA_PASSPORT                            0xf5ab
#define FA_PASTAFARIANISM                      0xf67b
#define FA_PASTE                               0xf0ea
#define FA_PAUSE                               0xf04c
#define FA_PAUSE_CIRCLE                        0xf28b
#define FA_PAW                                 0xf1b0
#define FA_PEACE                               0xf67c
#define FA_PEN                                 0xf304
#define FA_PEN_ALT                             0xf305
#define FA_PEN_FANCY                           0xf5ac
#define FA_PEN_NIB                             0xf5ad
#define FA_PEN_SQUARE                          0xf14b
#define FA_PENCIL_ALT                          0xf303
#define FA_PENCIL_RULER                        0xf5ae
#define FA_PEOPLE_CARRY                        0xf4ce
#define FA_PEPPER_HOT                          0xf816
#define FA_PERCENT                             0xf295
#define FA_PERCENTAGE                          0xf541
#define FA_PERSON_BOOTH                        0xf756
#define FA_PHONE                               0xf095
#define FA_PHONE_ALT                           0xf879
#define FA_PHONE_SLASH                         0xf3dd
#define FA_PHONE_SQUARE                        0xf098
#define FA_PHONE_SQUARE_ALT                    0xf87b
#define FA_PHONE_VOLUME                        0xf2a0
#define FA_PHOTO_VIDEO                         0xf87c
#define FA_PIGGY_BANK                          0xf4d3
#define FA_PILLS                               0xf484
#define FA_PIZZA_SLICE                         0xf818
#define FA_PLACE_OF_WORSHIP                    0xf67f
#define FA_PLANE                               0xf072
#define FA_PLANE_ARRIVAL                       0xf5af
#define FA_PLANE_DEPARTURE                     0xf5b0
#define FA_PLAY                                0xf04b
#define FA_PLAY_CIRCLE                         0xf144
#define FA_PLUG                                0xf1e6
#define FA_PLUS                                0xf067
#define FA_PLUS_CIRCLE                         0xf055
#define FA_PLUS_SQUARE                         0xf0fe
#define FA_PODCAST                             0xf2ce
#define FA_POLL                                0xf681
#define FA_POLL_H                              0xf682
#define FA_POO                                 0xf2fe
#define FA_POO_STORM                           0xf75a
#define FA_POOP                                0xf619
#define FA_PORTRAIT                            0xf3e0
#define FA_POUND_SIGN                          0xf154
#define FA_POWER_OFF                           0xf011
#define FA_PRAY                                0xf683
#define FA_PRAYING_HANDS                       0xf684
#define FA_PRESCRIPTION                        0xf5b1
#define FA_PRESCRIPTION_BOTTLE                 0xf485
#define FA_PRESCRIPTION_BOTTLE_ALT             0xf486
#define FA_PRINT                               0xf02f
#define FA_PROCEDURES                          0xf487
#define FA_PROJECT_DIAGRAM                     0xf542
#define FA_PUZZLE_PIECE                        0xf12e
#define FA_QRCODE                              0xf029
#define FA_QUESTION                            0xf128
#define FA_QUESTION_CIRCLE                     0xf059
#define FA_QUIDDITCH                           0xf458
#define FA_QUOTE_LEFT                          0xf10d
#define FA_QUOTE_RIGHT                         0xf10e
#define FA_QURAN                               0xf687
#define FA_RADIATION                           0xf7b9
#define FA_RADIATION_ALT                       0xf7ba
#define FA_RAINBOW                             0xf75b
#define FA_RANDOM                              0xf074
#define FA_RECEIPT                             0xf543
#define FA_RECYCLE                             0xf1b8
#define FA_REDO                                0xf01e
#define FA_REDO_ALT                            0xf2f9
#define FA_REGISTERED                          0xf25d
#define FA_REMOVE_FORMAT                       0xf87d
#define FA_REPLY                               0xf3e5
#define FA_REPLY_ALL                           0xf122
#define FA_REPUBLICAN                          0xf75e
#define FA_RESTROOM                            0xf7bd
#define FA_RETWEET                             0xf079
#define FA_RIBBON                              0xf4d6
#define FA_RING                                0xf70b
#define FA_ROAD                                0xf018
#define FA_ROBOT                               0xf544
#define FA_ROCKET                              0xf135
#define FA_ROUTE                               0xf4d7
#define FA_RSS                                 0xf09e
#define FA_RSS_SQUARE                          0xf143
#define FA_RUBLE_SIGN                          0xf158
#define FA_RULER                               0xf545
#define FA_RULER_COMBINED                      0xf546
#define FA_RULER_HORIZONTAL                    0xf547
#define FA_RULER_VERTICAL                      0xf548
#define FA_RUNNING                             0xf70c
#define FA_RUPEE_SIGN                          0xf156
#define FA_SAD_CRY                             0xf5b3
#define FA_SAD_TEAR                            0xf5b4
#define FA_SATELLITE                           0xf7bf
#define FA_SATELLITE_DISH                      0xf7c0
#define FA_SAVE                                0xf0c7
#define FA_SCHOOL                              0xf549
#define FA_SCREWDRIVER                         0xf54a
#define FA_SCROLL                              0xf70e
#define FA_SD_CARD                             0xf7c2
#define FA_SEARCH                              0xf002
#define FA_SEARCH_DOLLAR                       0xf688
#define FA_SEARCH_LOCATION                     0xf689
#define FA_SEARCH_MINUS                        0xf010
#define FA_SEARCH_PLUS                         0xf00e
#define FA_SEEDLING                            0xf4d8
#define FA_SERVER                              0xf233
#define FA_SHAPES                              0xf61f
#define FA_SHARE                               0xf064
#define FA_SHARE_ALT                           0xf1e0
#define FA_SHARE_ALT_SQUARE                    0xf1e1
#define FA_SHARE_SQUARE                        0xf14d
#define FA_SHEKEL_SIGN                         0xf20b
#define FA_SHIELD_ALT                          0xf3ed
#define FA_SHIP                                0xf21a
#define FA_SHIPPING_FAST                       0xf48b
#define FA_SHOE_PRINTS                         0xf54b
#define FA_SHOPPING_BAG                        0xf290
#define FA_SHOPPING_BASKET                     0xf291
#define FA_SHOPPING_CART                       0xf07a
#define FA_SHOWER                              0xf2cc
#define FA_SHUTTLE_VAN                         0xf5b6
#define FA_SIGN                                0xf4d9
#define FA_SIGN_IN_ALT                         0xf2f6
#define FA_SIGN_LANGUAGE                       0xf2a7
#define FA_SIGN_OUT_ALT                        0xf2f5
#define FA_SIGNAL                              0xf012
#define FA_SIGNATURE                           0xf5b7
#define FA_SIM_CARD                            0xf7c4
#define FA_SITEMAP                             0xf0e8
#define FA_SKATING                             0xf7c5
#define FA_SKIING                              0xf7c9
#define FA_SKIING_NORDIC                       0xf7ca
#define FA_SKULL                               0xf54c
#define FA_SKULL_CROSSBONES                    0xf714
#define FA_SLASH                               0xf715
#define FA_SLEIGH                              0xf7cc
#define FA_SLIDERS_H                           0xf1de
#define FA_SMILE                               0xf118
#define FA_SMILE_BEAM                          0xf5b8
#define FA_SMILE_WINK                          0xf4da
#define FA_SMOG                                0xf75f
#define FA_SMOKING                             0xf48d
#define FA_SMOKING_BAN                         0xf54d
#define FA_SMS                                 0xf7cd
#define FA_SNOWBOARDING                        0xf7ce
#define FA_SNOWFLAKE                           0xf2dc
#define FA_SNOWMAN                             0xf7d0
#define FA_SNOWPLOW                            0xf7d2
#define FA_SOCKS                               0xf696
#define FA_SOLAR_PANEL                         0xf5ba
#define FA_SORT                                0xf0dc
#define FA_SORT_ALPHA_DOWN                     0xf15d
#define FA_SORT_ALPHA_DOWN_ALT                 0xf881
#define FA_SORT_ALPHA_UP                       0xf15e
#define FA_SORT_ALPHA_UP_ALT                   0xf882
#define FA_SORT_AMOUNT_DOWN                    0xf160
#define FA_SORT_AMOUNT_DOWN_ALT                0xf884
#define FA_SORT_AMOUNT_UP                      0xf161
#define FA_SORT_AMOUNT_UP_ALT                  0xf885
#define FA_SORT_DOWN                           0xf0dd
#define FA_SORT_NUMERIC_DOWN                   0xf162
#define FA_SORT_NUMERIC_DOWN_ALT               0xf886
#define FA_SORT_NUMERIC_UP                     0xf163
#define FA_SORT_NUMERIC_UP_ALT                 0xf887
#define FA_SORT_UP                             0xf0de
#define FA_SPA                                 0xf5bb
#define FA_SPACE_SHUTTLE                       0xf197
#define FA_SPELL_CHECK                         0xf891
#define FA_SPIDER                              0xf717
#define FA_SPINNER                             0xf110
#define FA_SPLOTCH                             0xf5bc
#define FA_SPRAY_CAN                           0xf5bd
#define FA_SQUARE                              0xf0c8
#define FA_SQUARE_FULL                         0xf45c
#define FA_SQUARE_ROOT_ALT                     0xf698
#define FA_STAMP                               0xf5bf
#define FA_STAR                                0xf005
#define FA_STAR_AND_CRESCENT                   0xf699
#define FA_STAR_HALF                           0xf089
#define FA_STAR_HALF_ALT                       0xf5c0
#define FA_STAR_OF_DAVID                       0xf69a
#define FA_STAR_OF_LIFE                        0xf621
#define FA_STEP_BACKWARD                       0xf048
#define FA_STEP_FORWARD                        0xf051
#define FA_STETHOSCOPE                         0xf0f1
#define FA_STICKY_NOTE                         0xf249
#define FA_STOP                                0xf04d
#define FA_STOP_CIRCLE                         0xf28d
#define FA_STOPWATCH                           0xf2f2
#define FA_STORE                               0xf54e
#define FA_STORE_ALT                           0xf54f
#define FA_STREAM                              0xf550
#define FA_STREET_VIEW                         0xf21d
#define FA_STRIKETHROUGH                       0xf0cc
#define FA_STROOPWAFEL                         0xf551
#define FA_SUBSCRIPT                           0xf12c
#define FA_SUBWAY                              0xf239
#define FA_SUITCASE                            0xf0f2
#define FA_SUITCASE_ROLLING                    0xf5c1
#define FA_SUN                                 0xf185
#define FA_SUPERSCRIPT                         0xf12b
#define FA_SURPRISE                            0xf5c2
#define FA_SWATCHBOOK                          0xf5c3
#define FA_SWIMMER                             0xf5c4
#define FA_SWIMMING_POOL                       0xf5c5
#define FA_SYNAGOGUE                           0xf69b
#define FA_SYNC                                0xf021
#define FA_SYNC_ALT                            0xf2f1
#define FA_SYRINGE                             0xf48e
#define FA_TABLE                               0xf0ce
#define FA_TABLE_TENNIS                        0xf45d
#define FA_TABLET                              0xf10a
#define FA_TABLET_ALT                          0xf3fa
#define FA_TABLETS                             0xf490
#define FA_TACHOMETER_ALT                      0xf3fd
#define FA_TAG                                 0xf02b
#define FA_TAGS                                0xf02c
#define FA_TAPE                                0xf4db
#define FA_TASKS                               0xf0ae
#define FA_TAXI                                0xf1ba
#define FA_TEETH                               0xf62e
#define FA_TEETH_OPEN                          0xf62f
#define FA_TEMPERATURE_HIGH                    0xf769
#define FA_TEMPERATURE_LOW                     0xf76b
#define FA_TENGE                               0xf7d7
#define FA_TERMINAL                            0xf120
#define FA_TEXT_HEIGHT                         0xf034
#define FA_TEXT_WIDTH                          0xf035
#define FA_TH                                  0xf00a
#define FA_TH_LARGE                            0xf009
#define FA_TH_LIST                             0xf00b
#define FA_THEATER_MASKS                       0xf630
#define FA_THERMOMETER                         0xf491
#define FA_THERMOMETER_EMPTY                   0xf2cb
#define FA_THERMOMETER_FULL                    0xf2c7
#define FA_THERMOMETER_HALF                    0xf2c9
#define FA_THERMOMETER_QUARTER                 0xf2ca
#define FA_THERMOMETER_THREE_QUARTERS          0xf2c8
#define FA_THUMBS_DOWN                         0xf165
#define FA_THUMBS_UP                           0xf164
#define FA_THUMBTACK                           0xf08d
#define FA_TICKET_ALT                          0xf3ff
#define FA_TIMES                               0xf00d
#define FA_TIMES_CIRCLE                        0xf057
#define FA_TINT                                0xf043
#define FA_TINT_SLASH                          0xf5c7
#define FA_TIRED                               0xf5c8
#define FA_TOGGLE_OFF                          0xf204
#define FA_TOGGLE_ON                           0xf205
#define FA_TOILET                              0xf7d8
#define FA_TOILET_PAPER                        0xf71e
#define FA_TOOLBOX                             0xf552
#define FA_TOOLS                               0xf7d9
#define FA_TOOTH                               0xf5c9
#define FA_TORAH                               0xf6a0
#define FA_TORII_GATE                          0xf6a1
#define FA_TRACTOR                             0xf722
#define FA_TRADEMARK                           0xf25c
#define FA_TRAFFIC_LIGHT                       0xf637
#define FA_TRAIN                               0xf238
#define FA_TRAM                                0xf7da
#define FA_TRANSGENDER                         0xf224
#define FA_TRANSGENDER_ALT                     0xf225
#define FA_TRASH                               0xf1f8
#define FA_TRASH_ALT                           0xf2ed
#define FA_TRASH_RESTORE                       0xf829
#define FA_TRASH_RESTORE_ALT                   0xf82a
#define FA_TREE                                0xf1bb
#define FA_TROPHY                              0xf091
#define FA_TRUCK                               0xf0d1
#define FA_TRUCK_LOADING                       0xf4de
#define FA_TRUCK_MONSTER                       0xf63b
#define FA_TRUCK_MOVING                        0xf4df
#define FA_TRUCK_PICKUP                        0xf63c
#define FA_TSHIRT                              0xf553
#define FA_TTY                                 0xf1e4
#define FA_TV                                  0xf26c
#define FA_UMBRELLA                            0xf0e9
#define FA_UMBRELLA_BEACH                      0xf5ca
#define FA_UNDERLINE                           0xf0cd
#define FA_UNDO                                0xf0e2
#define FA_UNDO_ALT                            0xf2ea
#define FA_UNIVERSAL_ACCESS                    0xf29a
#define FA_UNIVERSITY                          0xf19c
#define FA_UNLINK                              0xf127
#define FA_UNLOCK                              0xf09c
#define FA_UNLOCK_ALT                          0xf13e
#define FA_UPLOAD                              0xf093
#define FA_USER                                0xf007
#define FA_USER_ALT                            0xf406
#define FA_USER_ALT_SLASH                      0xf4fa
#define FA_USER_ASTRONAUT                      0xf4fb
#define FA_USER_CHECK                          0xf4fc
#define FA_USER_CIRCLE                         0xf2bd
#define FA_USER_CLOCK                          0xf4fd
#define FA_USER_COG                            0xf4fe
#define FA_USER_EDIT                           0xf4ff
#define FA_USER_FRIENDS                        0xf500
#define FA_USER_GRADUATE                       0xf501
#define FA_USER_INJURED                        0xf728
#define FA_USER_LOCK                           0xf502
#define FA_USER_MD                             0xf0f0
#define FA_USER_MINUS                          0xf503
#define FA_USER_NINJA                          0xf504
#define FA_USER_NURSE                          0xf82f
#define FA_USER_PLUS                           0xf234
#define FA_USER_SECRET                         0xf21b
#define FA_USER_SHIELD                         0xf505
#define FA_USER_SLASH                          0xf506
#define FA_USER_TAG                            0xf507
#define FA_USER_TIE                            0xf508
#define FA_USER_TIMES                          0xf235
#define FA_USERS                               0xf0c0
#define FA_USERS_COG                           0xf509
#define FA_UTENSIL_SPOON                       0xf2e5
#define FA_UTENSILS                            0xf2e7
#define FA_VECTOR_SQUARE                       0xf5cb
#define FA_VENUS                               0xf221
#define FA_VENUS_DOUBLE                        0xf226
#define FA_VENUS_MARS                          0xf228
#define FA_VIAL                                0xf492
#define FA_VIALS                               0xf493
#define FA_VIDEO                               0xf03d
#define FA_VIDEO_SLASH                         0xf4e2
#define FA_VIHARA                              0xf6a7
#define FA_VOICEMAIL                           0xf897
#define FA_VOLLEYBALL_BALL                     0xf45f
#define FA_VOLUME_DOWN                         0xf027
#define FA_VOLUME_MUTE                         0xf6a9
#define FA_VOLUME_OFF                          0xf026
#define FA_VOLUME_UP                           0xf028
#define FA_VOTE_YEA                            0xf772
#define FA_VR_CARDBOARD                        0xf729
#define FA_WALKING                             0xf554
#define FA_WALLET                              0xf555
#define FA_WAREHOUSE                           0xf494
#define FA_WATER                               0xf773
#define FA_WAVE_SQUARE                         0xf83e
#define FA_WEIGHT                              0xf496
#define FA_WEIGHT_HANGING                      0xf5cd
#define FA_WHEELCHAIR                          0xf193
#define FA_WIFI                                0xf1eb
#define FA_WIND                                0xf72e
#define FA_WINDOW_CLOSE                        0xf410
#define FA_WINDOW_MAXIMIZE                     0xf2d0
#define FA_WINDOW_MINIMIZE                     0xf2d1
#define FA_WINDOW_RESTORE                      0xf2d2
#define FA_WINE_BOTTLE                         0xf72f
#define FA_WINE_GLASS                          0xf4e3
#define FA_WINE_GLASS_ALT                      0xf5ce
#define FA_WON_SIGN                            0xf159
#define FA_WRENCH                              0xf0ad
#define FA_X_RAY                               0xf497
#define FA_YEN_SIGN                            0xf157
#define FA_YIN_YANG                            0xf6ad
